// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivitySummary() {
  return window['go']['main']['App']['ActivitySummary']();
}

export function AddMemory(arg1, arg2) {
  return window['go']['main']['App']['AddMemory'](arg1, arg2);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function DeleteAnimation(arg1, arg2) {
  return window['go']['main']['App']['DeleteAnimation'](arg1, arg2);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function ExportAnimation(arg1, arg2) {
  return window['go']['main']['App']['ExportAnimation'](arg1, arg2);
}

export function GetAnimations(arg1) {
  return window['go']['main']['App']['GetAnimations'](arg1);
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetMonitor() {
  return window['go']['main']['App']['GetMonitor']();
}

export function HideFor(arg1) {
  return window['go']['main']['App']['HideFor'](arg1);
}

export function ImportAnimation(arg1) {
  return window['go']['main']['App']['ImportAnimation'](arg1);
}

export function ListAllAnimations() {
  return window['go']['main']['App']['ListAllAnimations']();
}

export function ListMemories() {
  return window['go']['main']['App']['ListMemories']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function PetClicked(arg1) {
  return window['go']['main']['App']['PetClicked'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReportPetState(arg1) {
  return window['go']['main']['App']['ReportPetState'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetFocusable(arg1) {
  return window['go']['main']['App']['SetFocusable'](arg1);
}

export function SetForceInteractive(arg1) {
  return window['go']['main']['App']['SetForceInteractive'](arg1);
}

export function SetHitRegions(arg1) {
  return window['go']['main']['App']['SetHitRegions'](arg1);
}

export function TestProvider(arg1, arg2) {
  return window['go']['main']['App']['TestProvider'](arg1, arg2);
}

export function UpdateMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMemory'](arg1, arg2, arg3);
}

export function WipeAllData() {
  return window['go']['main']['App']['WipeAllData']();
}

export function WipeMemories() {
  return window['go']['main']['App']['WipeMemories']();
}
